config/routes.rb
Rails.application.routes.draw do
  root to: 'invoices#index'
  resources :invoices, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord

  has_many :invoice_items, dependent: :destroy

    STATUS_CLASS = {
        :draft => "badge badge-secondary",
        :sent => "badge badge-primary",
        :paid => "badge badge-success"
    }

    def subtotal
        self.invoice_items.map { |item| item.qty * item.price }.sum
    end

    def discount_calculated
        subtotal * (self.discount / 100.0)
    end

    def vat_calculated
        (subtotal - discount_calculated) * (self.vat / 100.0)
    end

    def total
        subtotal - discount_calculated + vat_calculated
    end

    def status_class
        STATUS_CLASS[self.status.to_sym]
    end
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = scope
  end

  def show
    @invoice = scope.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@invoice.id}",
        page_size: 'A4',
        template: "invoices/show.html.erb",
        layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  private
    def scope
      ::Invoice.all.includes(:invoice_items)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Status</th>
      <th scope="col">Discount (%)</th>
      <th scope="col">VAT (%)</th>
      <th scope="col">TOTAL</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
        <td><%= invoice.from_full_name %></td>
        <td><%= invoice.to_full_name %></td>
        <td><span class="<%= invoice.status_class %>"><%= invoice.status %></span></td>
        <td><%= invoice.discount %></td>
        <td><%= invoice.vat %></td>
        <td><%= number_to_currency(invoice.total) %></td>
        <td><%= link_to 'View', invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/show.html.erb
<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
          <tr class="top">
            <td colspan="4">
              <table>
                <tr>
                  <td class="title">
                    <%= image_tag wicked_pdf_asset_base64('company_logo.png') %>
                  </td>

                  <td>
                    Invoice #: <b><%= @invoice.id %></b>
                    <br>
                    Created: <b><%= @invoice.created_at.strftime('%d/%m/%Y') %></b>
                    <br>
                    Due: <b><%= (@invoice.created_at + 1.month).strftime('%d/%m/%Y') %></b>
                    <br>
                    Status: <span class="<%= @invoice.status_class %>"><%= @invoice.status %></span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="information">
            <td colspan="4">
              <table>
                <tr>
                  <td>
                    <b><%= @invoice.from_full_name %></b><br>
                    <%= @invoice.from_address %><br>
                    <i class="far fa-envelope"></i> <%= @invoice.from_email %><br>
                    <i class="fas fa-phone"></i> <%= @invoice.from_phone %>
                  </td>

                  <td>
                    <b><%= @invoice.to_full_name %></b><br>
                    <%= @invoice.to_address %><br>
                    <i class="far fa-envelope"></i> <%= @invoice.to_email %><br>
                    <i class="fas fa-phone"></i> <%= @invoice.to_phone %>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="heading">
            <td>Payment Method</td>
            <td colspan="2"></td>
            <td class="right">Cache</td>
          </tr>

          <tr class="details">
            <td>Delivery Method</td>
            <td colspan="2"></td>
            <td class="right">1000</td>
          </tr>

          <tr class="heading">
            <td>Item</td>
            <td class="right">Price</td>
            <td class="right">Qty</td>
            <td>Total</td>
          </tr>

          <% @invoice.invoice_items.each do |invoice_item| %>
            <tr class="item">
                <td>
                    <%= invoice_item.name %><br>
                    <small><%= invoice_item.description %></small>
                </td>

                <td class="right">
                    <%= number_to_currency(invoice_item.price) %>
                </td>

                <td class="right">
                    x <%= invoice_item.qty %>
                </td>

                <td>
                    <%= number_to_currency(invoice_item.price * invoice_item.qty) %>
                </td>
            </tr>
          <% end %>

          <tr>
            <td colspan="4"></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b></td>
            <td><%= number_to_currency(@invoice.subtotal) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Discount (<%= @invoice.discount %>%)</b></td>
            <td>- <%= number_to_currency(@invoice.discount_calculated) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>VAT (<%= @invoice.vat %>%)</b></td>
            <td>+ <%= number_to_currency(@invoice.vat_calculated) %></td>
          </tr>

          <tr class="heading">
            <td colspan="2"></td>
            <td><b>TOTAL:</b></td>
            <td>
               <b><%= number_to_currency(@invoice.total) %></b>
            </td>
          </tr>
        </table>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <!-- render header links-->
  <%= render "layouts/shared/headers/header_links" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <!-- render navbar-->
  <%= render "layouts/shared/headers/header" %>
  <div class="container mt-3">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/shared/headers/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="far fa-file-pdf"></i>
        <span class="m-l-2">Rails Generate PDFs</span>
      <% end %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      </ul>

      <% if action_name.to_sym == :show %>
        <%= link_to 'Retour', root_path, class: "btn btn-outline-secondary mx-2" %>
        <%= link_to 'ENREGISTREZ LE REÇU', invoice_path(::Invoice.find(params[:id]), format: :pdf), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/shared/headers/_header_links.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">